// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

// src/bun-env.d.ts

// Esto le dice a TS: "Cualquier import que termine en .css es válido"
declare module "*.css";

// Aprovechando que usas imágenes, agrega esto también para que no te falle luego:
declare module "*.svg" {
  const content: string;
  export default content;
}

declare module "*.png";
declare module "*.jpg";


